# Generated by Django 5.2.4 on 2025-08-07 08:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='complaint',
            name='is_seen_by_employee',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='complaint',
            name='is_seen_by_recipient',
            field=models.BooleanField(default=False),
        ),
    ]
